language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t shreeji/docker-react -f Dcokerfile.dev .

script:
  - docker run -e CI=true shreeji/docker-react npm run test -- --coverage
