FROM node:alpine

WORKDIR '/app'


COPY package.json . 
RUN npm install -g npm@7.12.0
RUN npm install

COPY . .

RUN chmod -R a+rw /app/node_modules

CMD ["npm", "run", "start"]

#docker run -it -p 3000:3000 IMAGE_ID